### ISSUE TITLE
Question - useAff

### ISSUE THREAD

**Issue by piq9117** [spicydonuts/purescript-react-basic-hooks#18]
Am I understanding this correctly? If so, can I submit this as PR?
```Purescript
-- | `useAff` is used for asynchronous effects. This function uses `useEffect` which tracks
-- | the `key`. When the `key` changes, `useAff` will perform another asynchronous effect.
useAff ::
  forall key a.
  Eq key =>
  key ->
  Aff a ->
  Hook (UseAff key a) (Result a)
```

**Comment by spicydonuts** [comment]
Yep, and sure, though I don't know that the internal bits are relevant. You just give it an `Aff` and it will re-run it any time the key changes. It also cancels the previous `Aff` if the key changes while an async operation is in progress, so you don't need to worry about synchronization.

**Comment by piq9117** [comment]
thanks! :smiley:

**Comment by spicydonuts** [comment]
ty!
