### ISSUE TITLE
UseEffect/UseLayoutEffect Clean Up

### ISSUE THREAD

**Issue by born2defy** [spicydonuts/purescript-react-basic-hooks#2]
First, great library.  Perfect use of an indexed monad.  I didn’t notice any support for cleanup functions on useEffect or its sibling useLayoutEffect.  Seems you could just add an extra parameter taking a Maybe (Effect Unit) to each function to support it.  Was there a reason you chose not to include it?

**Comment by spicydonuts** [comment]
Thanks! And it's there :slightly_smiling_face: `Effect (Effect Unit)`

**Comment by born2defy** [comment]
LOL - How did I miss that?  Keep the compliment and forget the issue then :)

**Comment by spicydonuts** [comment]
No worries lol
