### ISSUE TITLE
How to use useContext, ContextProvider, createContext?

### ISSUE THREAD

**Issue by seanyu4296** [spicydonuts/purescript-react-basic-hooks#3]
Just wondering do you have any examples where you use `useContext`, `ContextProvider`, `createContext`? I'm pretty new to purescript, and have been using purescript-react-basic for awhile only. I would love to use React's Context API. so i see the type of createContext is 
`` Effect (Context a)``. Does that mean i need to put it somewhere like on a didMount of my Root component to get ``Context a``? Thank you.

**Comment by spicydonuts** [comment]
At the moment you most likely will want to call `createContext` at the module level using `unsafePerformEffect`. This isn't ideal but I haven't thought of a good way around it yet. This is exactly how it works in JS React apps though, so it seemed like the best combination of tradeoffs until I think of something better.

I'll leave this open until I get an example added at least though :)

**Comment by seanyu4296** [comment]
Alright that's what i ended up doing actually and it worked fine, still thinking about it if it's worth using in production. Maybe I can PR an example soon, after i migrate to using hooks. I'm currently using the FFI you did for React Context, but with the `consumer` `provider` pattern.  

Thanks for this library and quick response!

**Comment by spicydonuts** [comment]
There's a context example up now: https://github.com/spicydonuts/purescript-react-basic-hooks/blob/master/examples/context/src/Context.purs

**Comment by pete-murphy** [comment]
The deleted file is still available in Git history here: https://github.com/purescript-react/purescript-react-basic-hooks/blob/v4.2.2/examples/context/src/Context.purs.

There's also an example in the cookbook here: https://github.com/JordanMartinez/purescript-cookbook/blob/d6256a70d609fabeb3674dad62fb4d436895b1c6/recipes/RoutingPushReactHooks/src/Main.purs#L188-L191
