### ISSUE TITLE
React.memo recommended usage

### ISSUE THREAD

**Issue by 2jt** [spicydonuts/purescript-react-basic-hooks#50]
Hi, what would be the recommended way to use React.memo? 
In this [snippet](https://try.ps.ai/?purs=LYewJgrgNgpgBAWQIYEsB2cDuALGAnGAKEJWAAcQ8AXOABQKgjCNIurgBEkqkA6ZAJ4AjeAApBI0b14BKGSXKUaXHvyTD4SAM6J1IhWxoBRAGYmYAYxqjT5q-NZK4ty1V4BhEGi0hYcUVAgAOYOiuwuVrxGAB4WMGRUKF5w2s6x8YleBk4ASjBIkQBC2igWvBwA8ggpOjnZ7HkFbsVapeVVUQBuMGhUOqmVCF09ffU0jUUlZUbdvf06MyNaY3ATzVO8ABIgIADWOqKeimgjADT+APQAOnIra7wtbdt786v5VisA6jBCWwAqCAAMjU4JsAYCvj9-kDoYCOCALBBgCMQWCgfDEcjepDfmjAbCjLAsTRUnjCTBiTjYbxPugwCBMCDaWh6ZhiABadlwAA+nBQYDgaBANBMdLguCgZHwcGRoDgJggaCsSQwOFK2CwlH2WBQVA1FhAxxGhE5PLgPjgBrIAguZG0VBgAqQLJSYGYAtlIDgUBQu3gepQywNRt6CApXoAXBHCHB5ZQkFAoOKdtqyHgQGQtLwY3AAMpUPDoIJwdkAPhzojTGZ0ZbeTV4eRZ0oAqmhdcmXnXIgApXMADRkJfLsaOFBOvTgVczhGDY5GYblaCQyLgBCbeAAYhgALxwek5ixwAA8XPunrgABIu24CE1R14UUuV6I18xNxgj5+4AB9XgnLQOmA8ixmQEAEP49wwESKKHp+R5wAA3oKMAAY6EY-nAAC+8iEMAqAYFGzhmK4cCtrquH4XAu77rGoh4hiSIjLwQjgAIVFfsyrK8PSmIotuX54rwmB0gywGxnApalruFjaPA35wCAJg5uJ4kAHLCtgRZDmkcQJCqvB6umjIAERCiKICKmAxnKSpcDdhAAFwCxYBsbWNG2SpSBkGQx5csAuwAILeTZHk5Lwr7SqIXk+YquqDnR4LksSBkgElKLOQIOH+RuOxwFGOb3uOVA2UhnQJhA8CEfmhZoEENnnFoMBUAAauVlXodVWm1hENBkcVKmYbhuw5V6245vcs4PhOxkjcZcBXKVbUNU1rWMPAmHafc7mxvcipaEg5iNm+PWXt6wRwMZR34FpJg7NZKmgQQIWnWF6Cgf1HniUhXjuNgzpBDA0afZ9ixzLwf0srAeCcB0oN9AZSB4ADLVtfNPBIytqNuSAz3A7GjUo2t-gSDAvAmOmwAkxdc3o8jq0VWJwPnGVa24+Jg1DcU0P5SOhpztiKnfXq+D0+1eYFkWNmDf5XNUXuOM7e8biTUVF1c3NC0KcLeCi1hm1K9xCvibt3gHTAV14CdV6BMWxkBjoWjYBZUACgQ7IRQQVk2Y9RAeVeYVgCgnTyQA2qsBkwNENBXsZ6twAAusQMuIwukZA3AhXGoLWu4DrqNVRLtVS5zKfhnL7kq-OZex6XoAa0Lue6xttZbUbiv1ntZsW1bZ22-b5pO9AApmauMDuz0b6Ovd4k+89-vcUHofhw6UencZqdOYjc2J0NQU+YRmcTn1u-eeXRu3V6J4ysNOw5kIiO+dfXN37Xl9+bsXOp+NBuV9Ne8a-JFuBttpwBZhVOA1xzSYyJlfXajV8zcBgAAcmpjZDSItUaQIJhUbWutYEGwcjABBDoUHGWdOg6GYCYDTxAmBX2tl56B2DmzWMYcL6IVAUtKBhNwGDTxnAc499oYNwwUTPheNBGvw4RQpuLCE6ECAA) `barMemo { otherValue }` should not have printed in its render when the text input changes. As @ptrfrncsmrph has pointed out, changing the call to `barMemo otherValue` would make it work. So it is because of `{ otherValue }`, every time `barMemo` is called with `{ otherValue }`, a new object is created and as `React.memo` uses reference equality, it is normal, that the component `barMemo` re-renders.

I've found myself reaching for this feature, because I have a big form and one input triggers the re-render of the rest of them. Wrapping the parts of the form in `memo`, I hope the performance would improve. Or am I wrong?

Thanks

**Comment by spicydonuts** [comment]
This is the problem: `React.element c <<< { nested: _ }`

`memo` is just [React's memo](https://reactjs.org/docs/react-api.html#reactmemo), so it expects an actual `ReactComponent` and looks through the props object with shallow reference equality.

It works if you use it directly on a `ReactComponent` version of your component: https://try.ps.ai/?purs=LYewJgrgNgpgBAWQIYEsB2cDuALGAnGAKEJWAAcQ8AXOABQKgjCNIurgBEkqkA6ZAJ4AjeAApBI0b14BKGSXKUaXHvyTD4SAM6J1IhWxoBRAGYmYAYxqjT5q-NZK4ty1V4BhEGi0hYcUVAgAOYOiuwuVrxGAB4WMGRUKF5w2s6x8YleBk4ASjBIkQBC2igWvBwA8ggpOjnZ7HkFbsVapeVVUQBuMGhUOqmVCF09ffU0jUUlZUbdvf06MyNaY3ATzVO8ABIgIADWOqKeimgjADT%20APQAOnIra7wtbdt786v5VisA6jBCWwAqCAAMjU4JsAYCvj9-kDoYCOCALBBgCMQWCgfDEcjepDfmjAbCjLAsTRUnjCTBiTjYbxPugwCBMCDaWh6ZhiMBUBgAFxc5xmVxwACqaBQVEIHPQcAAvHB6YQ4P48RikSNeEJwAJpQAeLVwZms3j0zEoqU60Hg3iYOkM%20QKhUAPntMos2ngAH04CATPK7b6AHIgKjYdBBOAAWntaTiCSSaF4QbwDLgACI0IG4CYQBAWcmfb6FQApCBaGjqsCaiOykB5-MKpBkMhwLVhuDAXYAQQbNdrOV4BBZ%20H89cb2dFMkV4PJxPjICnKLLAnk4t2ADEdnAeT6jhQTtjfQBvOCdJCMeA8uAAZSoeBDNfOWhgVAAaieIGfeVeb2hQ5WIjRhaKNYAL7LmuIDSj69wWCAxwosmYHJnAVyHsep73o%20L6nnAQHhpG9xyr69zZloSDmHkA54H%20cAACRwIEobJuRzBfqGmYgLmvpkBABDdjRqy8OgXFirWB6emg7jYEg34wFyvEic4sx9LwkksrAeCcB0ixzPGSB4EEGGvvAVw8HpBlYZWBHySJD7PoZ-gSDAvAmImwAOSmiEmfptmnraVnnKhb5yXaIHLsU6mbgq25eCMNaHoGuB4Jhb4bh%20163r6IFtmF0pVpB7xuNBsG9CmYWIchnpBvgSXwDhlb4dWhH5bwxGkTATH4FRtH0SmQYoDoWjYFmUBgHABBhv2zEwGAHF2lxPG1rRvZgCgnQegA2vxVAwNENC0cmpVwAAuuyuxhQgFLgRFfJ2MJdqiG8TS8GsUW7rdtZxZViV2een7pSJIG%20vIWW6edoA5fcyJg5Z9wEE0L1wWdF1lR9CXVdhuEPZElkKkR3ite1lH8lYfHdcmvX9YN0AjWmNBjRN%20BTTNCpzUQC38ctq1wBtvZbTtfHJqD4FCLpiHHcunaNue8PFQBYpthLOWWWxTYtm2YE%20sL6nNq2p26RrIMXSrOuI6AeWPYVO5wRLZUenVTXY0ednXHANlo9rREPle3AwAA5O5NbxVVTtXC7j4VJ9bsth7MBe1tfvJlJgfqQFMBM3ALO8YthorW6QUKhtysoYZ6HeclAN%20XAmtwCjQdYeX8nnPcMBEvOBtgzXX113nR2EEAA&code=2729aea5fa7dfec2ffcc

**Comment by spicydonuts** [comment]
`memo`'s type is kind of weird though.. I think it should just be
```purs
memo ::
  forall props.
  ReactComponent props ->
  Effect (ReactComponent props)
```

**Comment by spicydonuts** [comment]
I've considered having both `memo` and `memoReactComponent`, where the latter is just React's function using ref equality and the former is `forall props. Eq props => (props -> JSX) -> Component props`.. but it's also already possible to write nearly the same thing using `useMemo`:

```purs
mkBarMemo ::
  Component
    { otherValue :: String
    }
mkBarMemo = do
  barMemo <- React.component "BarMemo" \{ otherValue } -> React.do
    React.unsafeRenderEffect $ log "this should not re-rendered"
    pure
      $ R.div_ [ R.text $ "Memo bar" ]
      
  React.component "BarMemoWrapper" \props -> React.do
    React.useMemo props \_ -> barMemo props
    -- ^ TryPureScript's version of react-basic-hooks is very old
    --   so to test it there you'll need to rename this to `useLazy`
```

**Comment by 2jt** [comment]
Thank you!
