### ISSUE TITLE
Hooks with lazy loading

### ISSUE THREAD

**Issue by mikesol** [spicydonuts/purescript-react-basic-hooks#53]
The current signature for `useState` is polymorphic over any `state`:

```purescript
useState ::
  forall state.
  state ->
  Hook (UseState state) (state /\ ((state -> state) -> Effect Unit))
```

However, if the state is a function in react, it tries to lazily evaluate the function: https://reactjs.org/docs/hooks-reference.html#lazy-initial-state. Should this case be encapsulated somehow in the library?

**Comment by spicydonuts** [comment]
Good point, this is probably a bug right now! I'll take a look at it soon

**Comment by spicydonuts** [comment]
Fixed in `7.0.1`

**Comment by mikesol** [comment]
Thanks!
I checked out the fix and it looks like a great start, but I'm not sure if it fixes the polymorphism. As I understand it, if I call `useState` on a value of `Effect Int`, the code in the JS will evaluate the effect and will treat it as`Int`, whereas the PS type will still be `Effect Int`. Furthermore, I think if you pass something of type `Function Int Int` to `useState`, it will crash when it tries to use the input in the thunk.

**Comment by spicydonuts** [comment]
Correct. I didn't think it made sense to complicate the types and docs with a third version of `useState` when you can currently achieve the same thing with `useMemo`:

```purs
initialState <- useMemo unit \_ -> slowInitState props
state /\ setState <- useState initialState
```

I'm not entirely opposed though, if that doesn't work for some reason. Actually, if I were building it from scratch today I'd probably just force the lazy `useState` always, but that's an unnecessarily large breaking change now, probably.

**Comment by mikesol** [comment]
Awesome, makes total sense and thanks for the helpful explanation!

**Comment by spicydonuts** [comment]
Re: `Lazy` fundeps, that would most likely be a breaking API change, so probably not worth it unless we're already making v8 for some other reason. Is that right? My fundep knowledge is rusty.

**Comment by mikesol** [comment]
Yup, it would be a breaking change in a few ways. Polymorphic type
signatures would break as they'd need the constraint, and anyone using a
Lazy value before would see a different behavior.
