### ISSUE TITLE
How to use deps

### ISSUE THREAD

**Issue by codingedgar** [spicydonuts/purescript-react-basic-hooks#55]
I'm sorry for the noob question, `useEffect` signature is:
```purescript
useEffect ::
  forall deps.
  Eq deps =>
  deps ->
  Effect (Effect Unit) ->
  Hook (UseEffect deps) Unit
useEffect deps effect =
  unsafeHook do
    runEffectFn3 useEffect_ (mkFn2 eq) deps effect
```

in js I often use

```javascript
useEffect (() => {
  // ...
  },
  [stringDependency, booleanDependency]
)
```

but `useEffect` has a homogenous `deps`, how can I have a `deps` list of different types?

I know this is more of a question about PureScript, but I think this is the best place to make this particular question and leave it for newcomers.

**Comment by ptrfrncsmrph** [comment]
The `deps` in that signature isn't necessarily homogeneous, but it _is_ polymorphic (so any `deps` type as long as it has an `Eq` instance). If you want a heterogeneous collection in PureScript, you could use a tuple or a record (which both have an `Eq` instance if the types they contain have `Eq` instances):
```haskell
Hooks.useEffect { stringDependency, booleanDependency } do
  -- ..
```
or
```haskell
Hooks.useEffect (stringDependency /\ booleanDependency) do
  -- ..
```

**Comment by codingedgar** [comment]
Thanks a lot! ✨

**Comment by spicydonuts** [comment]
Perfect, thanks @ptrfrncsmrph 🙂 

I'm actually working on docs _right now!_ I swear!!
