### ISSUE TITLE
Combine `useReducer` and `useAff`

### ISSUE THREAD

**Issue by i-am-the-slime** [spicydonuts/purescript-react-basic-hooks#6]
Nice library! I was wondering how to have a reducer that makes Ajax calls.
It looks like `useReducer` is pure.

**Comment by spicydonuts** [comment]
Thanks! `useReducer` is intended to be pure in plain JS as well. Can your `useAff` call use a value from state as its key to rerun your `Aff` any time it changes?

**Comment by spicydonuts** [comment]
I expanded on [the Aff example](https://github.com/spicydonuts/purescript-react-basic-hooks/blob/master/examples/aff/src/AffEx.purs) a bit, in case that helps.

**Comment by i-am-the-slime** [comment]
Thank you very much! I think I understand what's going on in the example. I should have stated my motivation behind the question which is achieving testability (mockability) of the Ajax calls.

I was thinking that with the reducer I could easily swap out the actual reducer in a test setting but I could not move the side-effects in there.

I guess I could pass the `mkCatDetails` in your example as props, but it seems to do a bit more than just the `Aff` call. Do you have a suggestion for this?

**Comment by spicydonuts** [comment]
You could have your API functions return a data type describing the request and inspect that. In my example I had `fetch :: Key a -> Aff a`. You could instead do something like `fetch :: Key a -> Request a` and `data Request a = Request { url :: ... }` and add an argument to your component creation for `runRequest :: Request a -> Aff a`, which either performs a real request or collects requests for inspection later in the test.

**Comment by i-am-the-slime** [comment]
This sounds very reasonable, thank you!

**Comment by i-am-the-slime** [comment]
For those who are interested (wow, it's almost one year later already, time flies):
```
module React.Basic.Extra.Hooks where

import Prelude
import Data.Foldable (for_)
import Data.Maybe (Maybe(..))
import Data.Newtype (class Newtype)
import Data.Tuple (Tuple)
import Effect (Effect)
import Effect.Aff (Aff)
import Effect.Class (liftEffect)
import React.Basic.Hooks (Hook, UseState, coerceHook, useState, (/\))
import React.Basic.Hooks as React
import React.Basic.Hooks.Aff (UseAff, useAff)

newtype UseAffReducer state action hooks
  = UseAffReducer
  ( UseAff (Maybe action) Unit
      ( UseState (Maybe action)
          (UseState state hooks)
      )
  )

derive instance ntUseAffReducer ∷ Newtype (UseAffReducer state action hooks) _
useAffReducer ∷ ∀ state action. Eq action => state -> (state -> action -> Aff state) -> Hook (UseAffReducer state action) (Tuple state (action -> Effect Unit))
useAffReducer initialState reducer =
  coerceHook React.do
    state /\ modifyState <- useState initialState
    maybeAction /\ modifyAction <- useState Nothing
    useAff maybeAction do
      for_ maybeAction \action -> do
        newState <- reducer state action
        liftEffect do
          modifyState (const newState)
          modifyAction (const Nothing)
    let
      dispatch = modifyAction <<< const <<< Just
    pure (state /\ dispatch)
```

**Comment by hivemind-js** [comment]
Would you consider adding this to the library?

**Comment by spicydonuts** [comment]
This exact implementation worries me a bit, but possibly. Asynchronously returning an entire state object can overwrite the work done by quicker actions, for example. I think we'd want the reducer to synchronously return a combined `{ state :: state, actions :: Array (Aff action) }` type, so any state changes resulting from async effects are run through the reducer with the latest state and apply their changes synchronously (basically the Elm architecture)

Can you both describe your use cases a bit?

**Comment by spicydonuts** [comment]
Possibly something like this? (I haven't tested it)

```purs
newtype UseAffReducer state action hooks
  = UseAffReducer
  ( UseEffect (UnsafeReference (Array (Aff (Array action))))
      (UseReducer { state :: state, effects :: Array (Aff (Array action)) } action hooks)
  )

derive instance ntUseAffReducer :: Newtype (UseAffReducer state action hooks) _

-- | Provide an initial state and a reducer function. This is a more powerful
-- | version of `useReducer`, where a state change can additionally queue
-- | asynchronous operations. The results of those operations must be  mapped
-- | into the reducer's `action` type. This is essentially the Elm architecture.
-- |
-- | *Note: Aff failures are thrown. If you need to capture an error state, be
-- |   sure to capture it in your action type!
useAffReducer ::
  forall state action.
  Eq action =>
  state ->
  (state -> action -> { state :: state, effects :: Array (Aff (Array action)) }) ->
  Hook (UseAffReducer state action) (state /\ (action -> Effect Unit))
useAffReducer initialState reducer =
  coerceHook React.do
    { state, effects } /\ dispatch <-
      useReducer { state: initialState, effects: [] } (_.state >>> reducer)
    useEffect (UnsafeReference effects) do
      for_ effects \aff ->
        launchAff_ do
          actions <- aff
          liftEffect do for_ actions dispatch
      mempty
    pure (state /\ dispatch)
```

**Comment by hivemind-js** [comment]
Thx for update! So basically my use case is that I want to query some data from a Rest endpoint upon button click/enter and display the result. I have been struggling a bit to do this with `useReducer` and `useEffect`/`useAff`. [Here an example](https://github.com/FloWi/covid-hackathon/blob/master/ui/src/Reducer.purs#L167-L180) of how I tried to combine it. Maybe it's just my lack of understanding on how to model this properly in react+hooks, but I haven't found a better way to do this and this looks kind of weird. 
I have created a PR  with a small example of the `useAffReducer`: #21 (I haven't been able to get it into the Makefile format). That looks somewhat better I suppose 🤔

**Comment by spicydonuts** [comment]
I added the input debounce just to highlight why I like this pattern. It would be difficult to do without race conditions using the reducer/action pattern. The delay could just as easily be moved to the parent's `useAff` as well (probably where I'd put it in a real app), but I was looking for a reason to make both the parent and child use `useAff` for different reasons.

**Comment by spicydonuts** [comment]
I'm also not rejecting `useAffReducer` necessarily, this is just for discussion. My primary hesitation is adding too many ways to do the same thing. There are also a lot of cases where `useReducer` might fit well but all you really care about effect-wise is dependent on the component landing in a particular state, at which point `useReducer` plus `useEffect` is pretty straightforward:

```purs
state /\ dispatch <- useReducer init reducer
useEffect state.something do
  somethingChanged something
```

**Comment by i-am-the-slime** [comment]
Thanks for all the answers @spicydonuts . I also don't think that this library should provide significantly more reducers than provided by react. A better version could, however, be a nice addition to the examples? In a  🎣 instead of a 🐡kind of way.

**Comment by spicydonuts** [comment]
I don't think I understand the fish lol. I was just thinking though, `useAffReducer` is a very very close analog to the current `React.Basic` api. It might be useful to have simply for conversion purposes. I'm also not sure if that's a fantastic idea or not, but yeah :)

**Comment by i-am-the-slime** [comment]
Yeah, I hadn't seen that you already have a PR open with it. Then I'd say it's an example that is guaranteed to be maintained across releases! The fish is about feeding people for a day or teaching them to write their own Hooks.

**Comment by i-am-the-slime** [comment]
@spicydonuts Can you actually explain the debouncing? Does a subsequent triggering of `useAff` cancel the previous if it's still running?

**Comment by i-am-the-slime** [comment]
I am very sorry:
```
-- | `useAff` is used for asynchronous effects or `Aff`. The asynchronous effect
-- | is re-run whenever the key changes. If another `Aff` runs when the key
-- | changes before the previous async resolves, it will cancel the previous in
-- | flight async effect.

```

**Comment by spicydonuts** [comment]
Yeah 😄 It makes it really difficult to run into race conditions. It's also easy to implement a debounce by starting with a delay, like `useAff deps (delay200ms *> fetchStuff)`, because the previous requests will get cancelled while they're still in their delay period and no requests have been launched (and of course from the consumer's perspective the behavior is the same even if a request has been launched, it'll just get cancelled).

**Comment by spicydonuts** [comment]
I've merged a version of `useAffReducer` into the latest release. Let me know if this doesn't resolve this issue.
